//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Paint.ToolboxLayout {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ToolboxLayoutDefinition {
        
        private BorderType borderField;
        
        private int maximizedHeightField;
        
        private int minimizedHeightField;
        
        private bool minimizedHeightFieldSpecified;
        
        private ColorType backgroundColorField;
        
        private ToolboxLayoutDefinitionControls controlsField;
        
        /// <remarks/>
        public BorderType Border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
            }
        }
        
        /// <remarks/>
        public int MaximizedHeight {
            get {
                return this.maximizedHeightField;
            }
            set {
                this.maximizedHeightField = value;
            }
        }
        
        /// <remarks/>
        public int MinimizedHeight {
            get {
                return this.minimizedHeightField;
            }
            set {
                this.minimizedHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimizedHeightSpecified {
            get {
                return this.minimizedHeightFieldSpecified;
            }
            set {
                this.minimizedHeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ColorType BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
            }
        }
        
        /// <remarks/>
        public ToolboxLayoutDefinitionControls Controls {
            get {
                return this.controlsField;
            }
            set {
                this.controlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorderType {
        
        private int widthField;
        
        private ColorType colorField;
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public ColorType Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ColorType {
        
        private byte redField;
        
        private byte greenField;
        
        private byte blueField;
        
        /// <remarks/>
        public byte Red {
            get {
                return this.redField;
            }
            set {
                this.redField = value;
            }
        }
        
        /// <remarks/>
        public byte Green {
            get {
                return this.greenField;
            }
            set {
                this.greenField = value;
            }
        }
        
        /// <remarks/>
        public byte Blue {
            get {
                return this.blueField;
            }
            set {
                this.blueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GaugeType {
        
        private int verticalMarginField;
        
        private int horizontalMarginField;
        
        private int widthField;
        
        private int markerWidthField;
        
        /// <remarks/>
        public int VerticalMargin {
            get {
                return this.verticalMarginField;
            }
            set {
                this.verticalMarginField = value;
            }
        }
        
        /// <remarks/>
        public int HorizontalMargin {
            get {
                return this.horizontalMarginField;
            }
            set {
                this.horizontalMarginField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int MarkerWidth {
            get {
                return this.markerWidthField;
            }
            set {
                this.markerWidthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegionType {
        
        private RegionTypeLocation locationField;
        
        private RegionTypeSize sizeField;
        
        private ColorType backgroundColorField;
        
        private BorderType borderField;
        
        /// <remarks/>
        public RegionTypeLocation Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public RegionTypeSize Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public ColorType BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
            }
        }
        
        /// <remarks/>
        public BorderType Border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegionTypeLocation {
        
        private float xField;
        
        private float yField;
        
        /// <remarks/>
        public float X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public float Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegionTypeSize {
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ToolboxLayoutDefinitionControls {
        
        private ToolboxLayoutDefinitionControlsColorSetter colorSetterField;
        
        private ToolboxLayoutDefinitionControlsBrushSizeSelector brushSizeSelectorField;
        
        private ToolboxLayoutDefinitionControlsColorSelector colorSelectorField;
        
        private ToolboxLayoutDefinitionControlsColorPicker[] colorPickerField;
        
        private ToolboxLayoutDefinitionControlsButton[] buttonField;
        
        /// <remarks/>
        public ToolboxLayoutDefinitionControlsColorSetter ColorSetter {
            get {
                return this.colorSetterField;
            }
            set {
                this.colorSetterField = value;
            }
        }
        
        /// <remarks/>
        public ToolboxLayoutDefinitionControlsBrushSizeSelector BrushSizeSelector {
            get {
                return this.brushSizeSelectorField;
            }
            set {
                this.brushSizeSelectorField = value;
            }
        }
        
        /// <remarks/>
        public ToolboxLayoutDefinitionControlsColorSelector ColorSelector {
            get {
                return this.colorSelectorField;
            }
            set {
                this.colorSelectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ColorPicker")]
        public ToolboxLayoutDefinitionControlsColorPicker[] ColorPicker {
            get {
                return this.colorPickerField;
            }
            set {
                this.colorPickerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Button")]
        public ToolboxLayoutDefinitionControlsButton[] Button {
            get {
                return this.buttonField;
            }
            set {
                this.buttonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ToolboxLayoutDefinitionControlsColorSetter {
        
        private RegionType regionField;
        
        /// <remarks/>
        public RegionType Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ToolboxLayoutDefinitionControlsBrushSizeSelector {
        
        private RegionType regionField;
        
        private ToolboxLayoutDefinitionControlsBrushSizeSelectorBrushSize brushSizeField;
        
        private GaugeType gaugeField;
        
        /// <remarks/>
        public RegionType Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public ToolboxLayoutDefinitionControlsBrushSizeSelectorBrushSize BrushSize {
            get {
                return this.brushSizeField;
            }
            set {
                this.brushSizeField = value;
            }
        }
        
        /// <remarks/>
        public GaugeType Gauge {
            get {
                return this.gaugeField;
            }
            set {
                this.gaugeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ToolboxLayoutDefinitionControlsBrushSizeSelectorBrushSize {
        
        private int minimumField;
        
        private int maximumField;
        
        private int initialField;
        
        /// <remarks/>
        public int Minimum {
            get {
                return this.minimumField;
            }
            set {
                this.minimumField = value;
            }
        }
        
        /// <remarks/>
        public int Maximum {
            get {
                return this.maximumField;
            }
            set {
                this.maximumField = value;
            }
        }
        
        /// <remarks/>
        public int Initial {
            get {
                return this.initialField;
            }
            set {
                this.initialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ToolboxLayoutDefinitionControlsColorSelector {
        
        private RegionType regionField;
        
        private GaugeType gaugeField;
        
        /// <remarks/>
        public RegionType Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public GaugeType Gauge {
            get {
                return this.gaugeField;
            }
            set {
                this.gaugeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ToolboxLayoutDefinitionControlsColorPicker {
        
        private RegionType regionField;
        
        /// <remarks/>
        public RegionType Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ToolboxLayoutDefinitionControlsButton {
        
        private ToolboxLayoutDefinitionControlsButtonButtonType buttonTypeField;
        
        private RegionType regionField;
        
        /// <remarks/>
        public ToolboxLayoutDefinitionControlsButtonButtonType ButtonType {
            get {
                return this.buttonTypeField;
            }
            set {
                this.buttonTypeField = value;
            }
        }
        
        /// <remarks/>
        public RegionType Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ToolboxLayoutDefinitionControlsButtonButtonType {
        
        /// <remarks/>
        Exit,
        
        /// <remarks/>
        Undo,
        
        /// <remarks/>
        Redo,
        
        /// <remarks/>
        ToggleMaxMin,
        
        /// <remarks/>
        ToggleDock,
        
        /// <remarks/>
        PlayPausePlayback,
    }
}
